jenkins:
  systemMessage: "Configured as Code"

jobs:
  - script: >
      job('super-seed') {
        scm {
          git {
            remote {
              url ('https://github.com/Jewel73/jenkins-dsl.git')
            }
          }
        }
        steps {
          dsl {
            external('jobdsl/**/*.groovy')
            removeAction('DELETE')
          }
        }
      }


tool:
  gradle:
    installations:
      - name: gradle
        home: /opt/gradle


credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              description: "This is the casc configuration credentials"
              id: mycrd
              password: john
              scope: GLOBAL
              username: john

          - usernamePassword:
              description: "Nexus server credentials"
              id: nexus-user
              password: admin
              scope: GLOBAL
              username: admin
 
security:
  globaljobdslsecurityconfiguration:
    useScriptSecurity: false

